import {
  USER_ROLES,
  PERMISSION_CATEGORIES,
  USER_PERMISSIONS,
  CONTENT_PERMISSIONS,
  MEDIA_PERMISSIONS,
  COMMENT_PERMISSIONS,
  EVENT_PERMISSIONS,
  VOLUNTEER_PERMISSIONS,
  MEMBERSHIP_PERMISSIONS,
  FINANCIAL_PERMISSIONS,
  ANALYTICS_PERMISSIONS,
  COMMUNICATION_PERMISSIONS,
  CHAT_PERMISSIONS,
  SYSTEM_PERMISSIONS,
  ADVERTISEMENT_PERMISSIONS,
  type Permission,
  type UserRole,
  type RolePermissionMatrix
} from '../types/permissions';

// ========================================
// ROLE DESCRIPTIONS
// ========================================

export const ROLE_DESCRIPTIONS = {
  [USER_ROLES.SUPER_ADMIN]: 'Highest level access with complete control over the platform - automatically granted ALL permissions',
  [USER_ROLES.ADMIN]: 'High-level administrative access for day-to-day operations management',
  [USER_ROLES.CONTENT_MANAGER]: 'Responsible for creating and managing website content',
  [USER_ROLES.EVENT_MANAGER]: 'Specialized role for creating and managing events',
  [USER_ROLES.VOLUNTEER_COORDINATOR]: 'Manages volunteer recruitment, scheduling, and tracking',
  [USER_ROLES.MEMBER_MANAGER]: 'Handles membership operations and member relations',
  [USER_ROLES.DONOR_MANAGER]: 'Manages donations and donor relationships',
  [USER_ROLES.CONTENT_INITIATOR]: 'Can create content but requires approval before publication',
  [USER_ROLES.MODERATOR]: 'Focuses on community management and content moderation',
  [USER_ROLES.ACCOUNTANT]: 'Read-only access to financial data for accounting purposes',
  [USER_ROLES.BLOGGER]: 'Can create and manage blog content and participate in group discussions',
  [USER_ROLES.REGULAR_USER]: 'Standard authenticated user with basic access',
  [USER_ROLES.GUEST]: 'Non-logged-in users browsing the website'
} as const;

// ========================================
// ROLE-PERMISSION MATRIX
// Based on the comprehensive guide provided
// ========================================

export const ROLE_PERMISSION_MATRIX: RolePermissionMatrix = {
  [USER_ROLES.SUPER_ADMIN]: {
    // Super Admin has COMPLETE access to ALL permissions across ALL categories
    // This is automatically handled by the isSuperAdmin check in rbac.ts
    // All permissions listed below are for explicit clarity and documentation
    [PERMISSION_CATEGORIES.USER_MANAGEMENT]: [
      USER_PERMISSIONS.USERS_VIEW_ALL,
      USER_PERMISSIONS.USERS_CREATE,
      USER_PERMISSIONS.USERS_EDIT_ALL,
      USER_PERMISSIONS.USERS_DELETE,
      USER_PERMISSIONS.USERS_SUSPEND,
      USER_PERMISSIONS.USERS_ASSIGN_ROLES,
      USER_PERMISSIONS.USERS_RESET_PASSWORD,
      USER_PERMISSIONS.USERS_EXPORT,
      USER_PERMISSIONS.USERS_VIEW_ACTIVITY
    ],
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_CREATE_PUBLISHED,
      CONTENT_PERMISSIONS.CONTENT_EDIT_OWN,
      CONTENT_PERMISSIONS.CONTENT_EDIT_ALL,
      CONTENT_PERMISSIONS.CONTENT_PUBLISH,
      CONTENT_PERMISSIONS.CONTENT_UNPUBLISH,
      CONTENT_PERMISSIONS.CONTENT_DELETE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_DELETE_PUBLISHED,
      CONTENT_PERMISSIONS.CONTENT_SCHEDULE,
      CONTENT_PERMISSIONS.CONTENT_MANAGE_CATEGORIES,
      CONTENT_PERMISSIONS.CONTENT_MANAGE_TAGS,
      CONTENT_PERMISSIONS.CONTENT_SUBMIT_REVIEW,
      CONTENT_PERMISSIONS.CONTENT_APPROVE_REVIEW,
      CONTENT_PERMISSIONS.CONTENT_VIEW_DRAFTS,
      CONTENT_PERMISSIONS.CONTENT_RESTORE
    ],
    [PERMISSION_CATEGORIES.MEDIA_MANAGEMENT]: [
      MEDIA_PERMISSIONS.MEDIA_UPLOAD,
      MEDIA_PERMISSIONS.MEDIA_EDIT_OWN,
      MEDIA_PERMISSIONS.MEDIA_EDIT_ALL,
      MEDIA_PERMISSIONS.MEDIA_DELETE_OWN,
      MEDIA_PERMISSIONS.MEDIA_DELETE_ALL,
      MEDIA_PERMISSIONS.MEDIA_ORGANIZE,
      MEDIA_PERMISSIONS.MEDIA_VIEW_ALL
    ],
    [PERMISSION_CATEGORIES.COMMENT_MODERATION]: [
      COMMENT_PERMISSIONS.COMMENTS_CREATE,
      COMMENT_PERMISSIONS.COMMENTS_EDIT_OWN,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_OWN,
      COMMENT_PERMISSIONS.COMMENTS_MODERATE,
      COMMENT_PERMISSIONS.COMMENTS_APPROVE,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_ALL
    ],
    [PERMISSION_CATEGORIES.EVENT_MANAGEMENT]: [
      EVENT_PERMISSIONS.EVENTS_VIEW_PUBLIC,
      EVENT_PERMISSIONS.EVENTS_VIEW_ALL,
      EVENT_PERMISSIONS.EVENTS_CREATE,
      EVENT_PERMISSIONS.EVENTS_EDIT_OWN,
      EVENT_PERMISSIONS.EVENTS_EDIT_ALL,
      EVENT_PERMISSIONS.EVENTS_DELETE,
      EVENT_PERMISSIONS.EVENTS_PUBLISH,
      EVENT_PERMISSIONS.EVENTS_MANAGE_REGISTRATION,
      EVENT_PERMISSIONS.EVENTS_REGISTER_SELF,
      EVENT_PERMISSIONS.EVENTS_REGISTER_OTHERS,
      EVENT_PERMISSIONS.EVENTS_CHECKIN,
      EVENT_PERMISSIONS.EVENTS_CANCEL,
      EVENT_PERMISSIONS.EVENTS_VIEW_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_EXPORT_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_SEND_NOTIFICATIONS
    ],
    [PERMISSION_CATEGORIES.VOLUNTEER_MANAGEMENT]: [
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPLY,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_CREATE_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_EDIT_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_DELETE_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_REVIEW_APPLICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPROVE_APPLICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_ASSIGN,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_MANAGE_SCHEDULE,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_TRACK_HOURS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_ALL,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_EXPORT,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_SEND_NOTIFICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_GENERATE_CERTIFICATES
    ],
    [PERMISSION_CATEGORIES.MEMBERSHIP_MANAGEMENT]: [
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_APPLY,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_VIEW_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_VIEW_ALL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_APPROVE,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EDIT_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EDIT_ALL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_RENEW_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_RENEW_OTHERS,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_CANCEL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_MANAGE_TIERS,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_MANAGE_BENEFITS,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EXPORT,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_SEND_NOTIFICATIONS
    ],
    [PERMISSION_CATEGORIES.FINANCIAL_MANAGEMENT]: [
      FINANCIAL_PERMISSIONS.PAYMENTS_MAKE,
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_OWN,
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.PAYMENTS_PROCESS,
      FINANCIAL_PERMISSIONS.PAYMENTS_REFUND,
      FINANCIAL_PERMISSIONS.PAYMENTS_EXPORT,
      FINANCIAL_PERMISSIONS.PAYMENTS_MANAGE_GATEWAY,
      FINANCIAL_PERMISSIONS.DONATIONS_MAKE,
      FINANCIAL_PERMISSIONS.DONATIONS_VIEW_OWN,
      FINANCIAL_PERMISSIONS.DONATIONS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.DONATIONS_MANAGE_CAMPAIGNS,
      FINANCIAL_PERMISSIONS.DONATIONS_ISSUE_RECEIPTS,
      FINANCIAL_PERMISSIONS.INVOICES_VIEW_OWN,
      FINANCIAL_PERMISSIONS.INVOICES_VIEW_ALL,
      FINANCIAL_PERMISSIONS.INVOICES_CREATE
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_BASIC,
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_ADVANCED,
      ANALYTICS_PERMISSIONS.ANALYTICS_EXPORT,
      ANALYTICS_PERMISSIONS.REPORTS_GENERATE,
      ANALYTICS_PERMISSIONS.REPORTS_CUSTOM,
      ANALYTICS_PERMISSIONS.REPORTS_FINANCIAL,
      ANALYTICS_PERMISSIONS.REPORTS_EXPORT
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_INDIVIDUAL,
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_BULK,
      COMMUNICATION_PERMISSIONS.EMAIL_MANAGE_TEMPLATES,
      COMMUNICATION_PERMISSIONS.EMAIL_MANAGE_CAMPAIGNS,
      COMMUNICATION_PERMISSIONS.SMS_SEND,
      COMMUNICATION_PERMISSIONS.NOTIFICATIONS_SEND,
      COMMUNICATION_PERMISSIONS.NEWSLETTER_SUBSCRIBE,
      COMMUNICATION_PERMISSIONS.NEWSLETTER_MANAGE
    ],
    [PERMISSION_CATEGORIES.CHAT_MANAGEMENT]: [
      CHAT_PERMISSIONS.CHAT_ACCESS,
      CHAT_PERMISSIONS.CHAT_SEND_MESSAGES,
      CHAT_PERMISSIONS.CHAT_DELETE_OWN_MESSAGES,
      CHAT_PERMISSIONS.CHAT_DELETE_ALL_MESSAGES,
      CHAT_PERMISSIONS.CHAT_MODERATE,
      CHAT_PERMISSIONS.CHAT_MANAGE_ROOMS,
      CHAT_PERMISSIONS.CHAT_VIEW_ALL_MESSAGES,
      CHAT_PERMISSIONS.CHAT_MANAGE_USERS,
      CHAT_PERMISSIONS.CHAT_EXPORT_HISTORY,
      CHAT_PERMISSIONS.CHAT_MANAGE_SETTINGS,
      CHAT_PERMISSIONS.CHAT_ASSIGN_MODERATORS,
      CHAT_PERMISSIONS.CHAT_VIEW_ANALYTICS
    ],
    [PERMISSION_CATEGORIES.SYSTEM_ADMINISTRATION]: [
      SYSTEM_PERMISSIONS.SYSTEM_VIEW_SETTINGS,
      SYSTEM_PERMISSIONS.SYSTEM_EDIT_SETTINGS,
      SYSTEM_PERMISSIONS.SYSTEM_VIEW_LOGS,
      SYSTEM_PERMISSIONS.SYSTEM_MANAGE_INTEGRATIONS,
      SYSTEM_PERMISSIONS.SYSTEM_MANAGE_SECURITY,
      SYSTEM_PERMISSIONS.SYSTEM_DATABASE_BACKUP,
      SYSTEM_PERMISSIONS.SYSTEM_MANAGE_ROLES,
      SYSTEM_PERMISSIONS.SYSTEM_MANAGE_PERMISSIONS
    ],
    [PERMISSION_CATEGORIES.ADVERTISEMENT_MANAGEMENT]: [
      ADVERTISEMENT_PERMISSIONS.ADS_VIEW,
      ADVERTISEMENT_PERMISSIONS.ADS_CREATE,
      ADVERTISEMENT_PERMISSIONS.ADS_EDIT,
      ADVERTISEMENT_PERMISSIONS.ADS_DELETE,
      ADVERTISEMENT_PERMISSIONS.ADS_APPROVE,
      ADVERTISEMENT_PERMISSIONS.ADVERTISERS_MANAGE,
      ADVERTISEMENT_PERMISSIONS.AD_ZONES_MANAGE,
      ADVERTISEMENT_PERMISSIONS.AD_ANALYTICS_VIEW,
      ADVERTISEMENT_PERMISSIONS.AD_CAMPAIGNS_MANAGE
    ]
  },

  // ========================================
  // ADMIN/MANAGER ROLE
  // ========================================

  [USER_ROLES.ADMIN]: {
    [PERMISSION_CATEGORIES.USER_MANAGEMENT]: [
      USER_PERMISSIONS.USERS_VIEW_ALL,
      USER_PERMISSIONS.USERS_CREATE,
      USER_PERMISSIONS.USERS_EDIT_ALL,
      USER_PERMISSIONS.USERS_SUSPEND,
      USER_PERMISSIONS.USERS_ASSIGN_ROLES,
      USER_PERMISSIONS.USERS_RESET_PASSWORD,
      USER_PERMISSIONS.USERS_EXPORT,
      USER_PERMISSIONS.USERS_VIEW_ACTIVITY
    ],
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_CREATE_PUBLISHED,
      CONTENT_PERMISSIONS.CONTENT_EDIT_OWN,
      CONTENT_PERMISSIONS.CONTENT_EDIT_ALL,
      CONTENT_PERMISSIONS.CONTENT_PUBLISH,
      CONTENT_PERMISSIONS.CONTENT_UNPUBLISH,
      CONTENT_PERMISSIONS.CONTENT_DELETE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_DELETE_PUBLISHED,
      CONTENT_PERMISSIONS.CONTENT_SCHEDULE,
      CONTENT_PERMISSIONS.CONTENT_MANAGE_CATEGORIES,
      CONTENT_PERMISSIONS.CONTENT_MANAGE_TAGS,
      CONTENT_PERMISSIONS.CONTENT_SUBMIT_REVIEW,
      CONTENT_PERMISSIONS.CONTENT_APPROVE_REVIEW,
      CONTENT_PERMISSIONS.CONTENT_VIEW_DRAFTS,
      CONTENT_PERMISSIONS.CONTENT_RESTORE
    ],
    [PERMISSION_CATEGORIES.MEDIA_MANAGEMENT]: [
      MEDIA_PERMISSIONS.MEDIA_UPLOAD,
      MEDIA_PERMISSIONS.MEDIA_EDIT_OWN,
      MEDIA_PERMISSIONS.MEDIA_EDIT_ALL,
      MEDIA_PERMISSIONS.MEDIA_DELETE_OWN,
      MEDIA_PERMISSIONS.MEDIA_DELETE_ALL,
      MEDIA_PERMISSIONS.MEDIA_ORGANIZE,
      MEDIA_PERMISSIONS.MEDIA_VIEW_ALL
    ],
    [PERMISSION_CATEGORIES.COMMENT_MODERATION]: [
      COMMENT_PERMISSIONS.COMMENTS_MODERATE,
      COMMENT_PERMISSIONS.COMMENTS_APPROVE,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_ALL
    ],
    [PERMISSION_CATEGORIES.EVENT_MANAGEMENT]: [
      EVENT_PERMISSIONS.EVENTS_VIEW_PUBLIC,
      EVENT_PERMISSIONS.EVENTS_VIEW_ALL,
      EVENT_PERMISSIONS.EVENTS_CREATE,
      EVENT_PERMISSIONS.EVENTS_EDIT_OWN,
      EVENT_PERMISSIONS.EVENTS_EDIT_ALL,
      EVENT_PERMISSIONS.EVENTS_DELETE,
      EVENT_PERMISSIONS.EVENTS_PUBLISH,
      EVENT_PERMISSIONS.EVENTS_MANAGE_REGISTRATION,
      EVENT_PERMISSIONS.EVENTS_REGISTER_SELF,
      EVENT_PERMISSIONS.EVENTS_REGISTER_OTHERS,
      EVENT_PERMISSIONS.EVENTS_CHECKIN,
      EVENT_PERMISSIONS.EVENTS_CANCEL,
      EVENT_PERMISSIONS.EVENTS_VIEW_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_EXPORT_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_SEND_NOTIFICATIONS
    ],
    [PERMISSION_CATEGORIES.VOLUNTEER_MANAGEMENT]: [
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPLY,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_CREATE_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_EDIT_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_DELETE_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_REVIEW_APPLICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPROVE_APPLICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_ASSIGN,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_MANAGE_SCHEDULE,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_TRACK_HOURS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_ALL,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_EXPORT,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_SEND_NOTIFICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_GENERATE_CERTIFICATES
    ],
    [PERMISSION_CATEGORIES.MEMBERSHIP_MANAGEMENT]: [
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_VIEW_ALL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_APPROVE,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EDIT_ALL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EXPORT,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_SEND_NOTIFICATIONS
    ],
    [PERMISSION_CATEGORIES.FINANCIAL_MANAGEMENT]: [
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.PAYMENTS_PROCESS,
      FINANCIAL_PERMISSIONS.PAYMENTS_EXPORT
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_ADVANCED,
      ANALYTICS_PERMISSIONS.ANALYTICS_EXPORT
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_BULK,
      COMMUNICATION_PERMISSIONS.EMAIL_MANAGE_CAMPAIGNS,
      COMMUNICATION_PERMISSIONS.NOTIFICATIONS_SEND
    ],
    [PERMISSION_CATEGORIES.ADVERTISEMENT_MANAGEMENT]: [
      ADVERTISEMENT_PERMISSIONS.ADS_VIEW,
      ADVERTISEMENT_PERMISSIONS.ADS_CREATE,
      ADVERTISEMENT_PERMISSIONS.ADS_EDIT,
      ADVERTISEMENT_PERMISSIONS.ADS_APPROVE,
      ADVERTISEMENT_PERMISSIONS.ADVERTISERS_MANAGE,
      ADVERTISEMENT_PERMISSIONS.AD_ZONES_MANAGE,
      ADVERTISEMENT_PERMISSIONS.AD_ANALYTICS_VIEW,
      ADVERTISEMENT_PERMISSIONS.AD_CAMPAIGNS_MANAGE
    ],
    [PERMISSION_CATEGORIES.CHAT_MANAGEMENT]: [
      CHAT_PERMISSIONS.CHAT_ACCESS,
      CHAT_PERMISSIONS.CHAT_SEND_MESSAGES,
      CHAT_PERMISSIONS.CHAT_DELETE_OWN_MESSAGES,
      CHAT_PERMISSIONS.CHAT_MODERATE,
      CHAT_PERMISSIONS.CHAT_VIEW_ALL_MESSAGES,
      CHAT_PERMISSIONS.CHAT_MANAGE_USERS,
      CHAT_PERMISSIONS.CHAT_EXPORT_HISTORY,
      CHAT_PERMISSIONS.CHAT_ASSIGN_MODERATORS
    ]
  },

  // ========================================
  // CONTENT MANAGER ROLE
  // ========================================

  [USER_ROLES.CONTENT_MANAGER]: {
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_PUBLISHED,
      CONTENT_PERMISSIONS.CONTENT_EDIT_ALL,
      CONTENT_PERMISSIONS.CONTENT_PUBLISH,
      CONTENT_PERMISSIONS.CONTENT_UNPUBLISH,
      CONTENT_PERMISSIONS.CONTENT_SCHEDULE,
      CONTENT_PERMISSIONS.CONTENT_MANAGE_CATEGORIES,
      CONTENT_PERMISSIONS.CONTENT_MANAGE_TAGS,
      CONTENT_PERMISSIONS.CONTENT_DELETE_DRAFT
    ],
    [PERMISSION_CATEGORIES.MEDIA_MANAGEMENT]: [
      MEDIA_PERMISSIONS.MEDIA_UPLOAD,
      MEDIA_PERMISSIONS.MEDIA_EDIT_ALL,
      MEDIA_PERMISSIONS.MEDIA_DELETE_OWN,
      MEDIA_PERMISSIONS.MEDIA_ORGANIZE,
      MEDIA_PERMISSIONS.MEDIA_VIEW_ALL
    ],
    [PERMISSION_CATEGORIES.COMMENT_MODERATION]: [
      COMMENT_PERMISSIONS.COMMENTS_MODERATE,
      COMMENT_PERMISSIONS.COMMENTS_APPROVE,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_OWN
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_BASIC
    ],
    [PERMISSION_CATEGORIES.ADVERTISEMENT_MANAGEMENT]: [
      ADVERTISEMENT_PERMISSIONS.ADS_VIEW,
      ADVERTISEMENT_PERMISSIONS.ADS_CREATE,
      ADVERTISEMENT_PERMISSIONS.ADS_EDIT,
      ADVERTISEMENT_PERMISSIONS.ADS_APPROVE,
      ADVERTISEMENT_PERMISSIONS.AD_ANALYTICS_VIEW
    ]
  },

  // ========================================
  // EVENT MANAGER ROLE
  // ========================================

  [USER_ROLES.EVENT_MANAGER]: {
    [PERMISSION_CATEGORIES.EVENT_MANAGEMENT]: [
      EVENT_PERMISSIONS.EVENTS_VIEW_PUBLIC,
      EVENT_PERMISSIONS.EVENTS_VIEW_ALL,
      EVENT_PERMISSIONS.EVENTS_CREATE,
      EVENT_PERMISSIONS.EVENTS_EDIT_OWN,
      EVENT_PERMISSIONS.EVENTS_EDIT_ALL,
      EVENT_PERMISSIONS.EVENTS_DELETE,
      EVENT_PERMISSIONS.EVENTS_PUBLISH,
      EVENT_PERMISSIONS.EVENTS_MANAGE_REGISTRATION,
      EVENT_PERMISSIONS.EVENTS_REGISTER_SELF,
      EVENT_PERMISSIONS.EVENTS_REGISTER_OTHERS,
      EVENT_PERMISSIONS.EVENTS_CHECKIN,
      EVENT_PERMISSIONS.EVENTS_CANCEL,
      EVENT_PERMISSIONS.EVENTS_VIEW_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_EXPORT_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_SEND_NOTIFICATIONS
    ],
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_EDIT_OWN
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_BASIC,
      ANALYTICS_PERMISSIONS.REPORTS_GENERATE
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_BULK
    ]
  },

  // ========================================
  // VOLUNTEER COORDINATOR ROLE
  // ========================================

  [USER_ROLES.VOLUNTEER_COORDINATOR]: {
    [PERMISSION_CATEGORIES.VOLUNTEER_MANAGEMENT]: [
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPLY,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_CREATE_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_EDIT_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_DELETE_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_REVIEW_APPLICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPROVE_APPLICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_ASSIGN,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_MANAGE_SCHEDULE,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_TRACK_HOURS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_ALL,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_EXPORT,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_SEND_NOTIFICATIONS,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_GENERATE_CERTIFICATES
    ],
    [PERMISSION_CATEGORIES.EVENT_MANAGEMENT]: [
      EVENT_PERMISSIONS.EVENTS_VIEW_ALL,
      EVENT_PERMISSIONS.EVENTS_VIEW_ATTENDEES,
      EVENT_PERMISSIONS.EVENTS_CHECKIN
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_BULK,
      COMMUNICATION_PERMISSIONS.SMS_SEND
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_BASIC,
      ANALYTICS_PERMISSIONS.REPORTS_GENERATE,
      ANALYTICS_PERMISSIONS.REPORTS_EXPORT
    ]
  },

  // ========================================
  // MEMBER MANAGER ROLE
  // ========================================

  [USER_ROLES.MEMBER_MANAGER]: {
    [PERMISSION_CATEGORIES.MEMBERSHIP_MANAGEMENT]: [
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_APPLY,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_VIEW_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_VIEW_ALL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_APPROVE,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EDIT_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EDIT_ALL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_RENEW_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_RENEW_OTHERS,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_CANCEL,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_MANAGE_TIERS,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_MANAGE_BENEFITS,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EXPORT,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_SEND_NOTIFICATIONS
    ],
    [PERMISSION_CATEGORIES.FINANCIAL_MANAGEMENT]: [
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.PAYMENTS_PROCESS,
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_OWN,
      FINANCIAL_PERMISSIONS.INVOICES_VIEW_ALL,
      FINANCIAL_PERMISSIONS.INVOICES_CREATE
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_BULK,
      COMMUNICATION_PERMISSIONS.NOTIFICATIONS_SEND
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_BASIC,
      ANALYTICS_PERMISSIONS.REPORTS_GENERATE,
      ANALYTICS_PERMISSIONS.REPORTS_EXPORT,
      ANALYTICS_PERMISSIONS.REPORTS_FINANCIAL
    ]
  },

  // ========================================
  // DONOR MANAGER ROLE
  // ========================================

  [USER_ROLES.DONOR_MANAGER]: {
    [PERMISSION_CATEGORIES.FINANCIAL_MANAGEMENT]: [
      FINANCIAL_PERMISSIONS.DONATIONS_MAKE,
      FINANCIAL_PERMISSIONS.DONATIONS_VIEW_OWN,
      FINANCIAL_PERMISSIONS.DONATIONS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.DONATIONS_MANAGE_CAMPAIGNS,
      FINANCIAL_PERMISSIONS.DONATIONS_ISSUE_RECEIPTS,
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.PAYMENTS_PROCESS,
      FINANCIAL_PERMISSIONS.INVOICES_VIEW_ALL,
      FINANCIAL_PERMISSIONS.INVOICES_CREATE
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_BULK,
      COMMUNICATION_PERMISSIONS.EMAIL_MANAGE_CAMPAIGNS
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_ADVANCED,
      ANALYTICS_PERMISSIONS.REPORTS_GENERATE,
      ANALYTICS_PERMISSIONS.REPORTS_FINANCIAL,
      ANALYTICS_PERMISSIONS.REPORTS_EXPORT
    ],
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_EDIT_OWN
    ]
  },

  // ========================================
  // CONTENT INITIATOR ROLE
  // ========================================

  [USER_ROLES.CONTENT_INITIATOR]: {
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_EDIT_OWN,
      CONTENT_PERMISSIONS.CONTENT_DELETE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_SUBMIT_REVIEW,
      CONTENT_PERMISSIONS.CONTENT_VIEW_DRAFTS
    ],
    [PERMISSION_CATEGORIES.MEDIA_MANAGEMENT]: [
      MEDIA_PERMISSIONS.MEDIA_UPLOAD,
      MEDIA_PERMISSIONS.MEDIA_EDIT_OWN,
      MEDIA_PERMISSIONS.MEDIA_DELETE_OWN,
      MEDIA_PERMISSIONS.MEDIA_VIEW_ALL
    ]
  },

  // ========================================
  // MODERATOR ROLE
  // ========================================

  [USER_ROLES.MODERATOR]: {
    [PERMISSION_CATEGORIES.COMMENT_MODERATION]: [
      COMMENT_PERMISSIONS.COMMENTS_MODERATE,
      COMMENT_PERMISSIONS.COMMENTS_APPROVE,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_ALL
    ],
    [PERMISSION_CATEGORIES.USER_MANAGEMENT]: [
      USER_PERMISSIONS.USERS_VIEW_BASIC,
      USER_PERMISSIONS.USERS_SUSPEND
    ],
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_VIEW_DRAFTS
    ]
  },

  // ========================================
  // ACCOUNTANT ROLE
  // ========================================

  [USER_ROLES.ACCOUNTANT]: {
    [PERMISSION_CATEGORIES.FINANCIAL_MANAGEMENT]: [
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.PAYMENTS_EXPORT,
      FINANCIAL_PERMISSIONS.DONATIONS_VIEW_ALL,
      FINANCIAL_PERMISSIONS.INVOICES_VIEW_ALL
    ],
    [PERMISSION_CATEGORIES.ANALYTICS_REPORTING]: [
      ANALYTICS_PERMISSIONS.ANALYTICS_VIEW_ADVANCED,
      ANALYTICS_PERMISSIONS.REPORTS_FINANCIAL,
      ANALYTICS_PERMISSIONS.REPORTS_EXPORT
    ]
  },

  // ========================================
  // BLOGGER ROLE
  // ========================================

  [USER_ROLES.BLOGGER]: {
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      CONTENT_PERMISSIONS.CONTENT_CREATE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_EDIT_OWN,
      CONTENT_PERMISSIONS.CONTENT_DELETE_DRAFT,
      CONTENT_PERMISSIONS.CONTENT_SUBMIT_REVIEW,
      CONTENT_PERMISSIONS.CONTENT_VIEW_DRAFTS
    ],
    [PERMISSION_CATEGORIES.MEDIA_MANAGEMENT]: [
      MEDIA_PERMISSIONS.MEDIA_UPLOAD,
      MEDIA_PERMISSIONS.MEDIA_EDIT_OWN,
      MEDIA_PERMISSIONS.MEDIA_DELETE_OWN,
      MEDIA_PERMISSIONS.MEDIA_VIEW_ALL
    ],
    [PERMISSION_CATEGORIES.COMMENT_MODERATION]: [
      COMMENT_PERMISSIONS.COMMENTS_CREATE,
      COMMENT_PERMISSIONS.COMMENTS_EDIT_OWN,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_OWN
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_INDIVIDUAL,
      COMMUNICATION_PERMISSIONS.NEWSLETTER_SUBSCRIBE
    ]
  },

  // ========================================
  // REGULAR USER ROLE
  // ========================================

  [USER_ROLES.REGULAR_USER]: {
    [PERMISSION_CATEGORIES.USER_MANAGEMENT]: [
      USER_PERMISSIONS.USERS_VIEW_BASIC,
      USER_PERMISSIONS.USERS_EDIT_OWN
    ],
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      COMMENT_PERMISSIONS.COMMENTS_CREATE,
      COMMENT_PERMISSIONS.COMMENTS_EDIT_OWN,
      COMMENT_PERMISSIONS.COMMENTS_DELETE_OWN
    ],
    [PERMISSION_CATEGORIES.CHAT_MANAGEMENT]: [
      CHAT_PERMISSIONS.CHAT_ACCESS,
      CHAT_PERMISSIONS.CHAT_SEND_MESSAGES,
      CHAT_PERMISSIONS.CHAT_DELETE_OWN_MESSAGES
    ],
    [PERMISSION_CATEGORIES.EVENT_MANAGEMENT]: [
      EVENT_PERMISSIONS.EVENTS_VIEW_PUBLIC,
      EVENT_PERMISSIONS.EVENTS_VIEW_ALL,
      EVENT_PERMISSIONS.EVENTS_REGISTER_SELF
    ],
    [PERMISSION_CATEGORIES.VOLUNTEER_MANAGEMENT]: [
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_VIEW_OPPORTUNITIES,
      VOLUNTEER_PERMISSIONS.VOLUNTEERS_APPLY
    ],
    [PERMISSION_CATEGORIES.MEMBERSHIP_MANAGEMENT]: [
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_VIEW_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_EDIT_OWN,
      MEMBERSHIP_PERMISSIONS.MEMBERSHIP_RENEW_OWN
    ],
    [PERMISSION_CATEGORIES.FINANCIAL_MANAGEMENT]: [
      FINANCIAL_PERMISSIONS.PAYMENTS_MAKE,
      FINANCIAL_PERMISSIONS.PAYMENTS_VIEW_OWN,
      FINANCIAL_PERMISSIONS.INVOICES_VIEW_OWN,
      FINANCIAL_PERMISSIONS.DONATIONS_MAKE,
      FINANCIAL_PERMISSIONS.DONATIONS_VIEW_OWN
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.NEWSLETTER_SUBSCRIBE,
      COMMUNICATION_PERMISSIONS.EMAIL_SEND_INDIVIDUAL
    ]
  },

  // ========================================
  // GUEST ROLE
  // ========================================

  [USER_ROLES.GUEST]: {
    [PERMISSION_CATEGORIES.CONTENT_MANAGEMENT]: [
      COMMENT_PERMISSIONS.COMMENTS_CREATE
    ],
    [PERMISSION_CATEGORIES.EVENT_MANAGEMENT]: [
      EVENT_PERMISSIONS.EVENTS_VIEW_PUBLIC
    ],
    [PERMISSION_CATEGORIES.COMMUNICATION]: [
      COMMUNICATION_PERMISSIONS.NEWSLETTER_SUBSCRIBE
    ],
    [PERMISSION_CATEGORIES.CHAT_MANAGEMENT]: [
      CHAT_PERMISSIONS.CHAT_ACCESS,
      CHAT_PERMISSIONS.CHAT_SEND_MESSAGES
    ]
  }
};

// ========================================
// UTILITY FUNCTIONS
// ========================================

export const getAllPermissionsForRole = (role: UserRole): Permission[] => {
  const rolePermissions = ROLE_PERMISSION_MATRIX[role];
  if (!rolePermissions) return [];

  return Object.values(rolePermissions).flat();
};

export const getPermissionsByCategory = (role: UserRole, category: string): Permission[] => {
  return ROLE_PERMISSION_MATRIX[role]?.[category] || [];
};

export const hasPermission = (role: UserRole, permission: Permission): boolean => {
  const rolePermissions = getAllPermissionsForRole(role);
  return rolePermissions.includes(permission);
};

export const getRoleHierarchy = (): UserRole[] => {
  return [
    USER_ROLES.GUEST,
    USER_ROLES.REGULAR_USER,
    USER_ROLES.BLOGGER,
    USER_ROLES.CONTENT_INITIATOR,
    USER_ROLES.MODERATOR,
    USER_ROLES.ACCOUNTANT,
    USER_ROLES.DONOR_MANAGER,
    USER_ROLES.MEMBER_MANAGER,
    USER_ROLES.VOLUNTEER_COORDINATOR,
    USER_ROLES.EVENT_MANAGER,
    USER_ROLES.CONTENT_MANAGER,
    USER_ROLES.ADMIN,
    USER_ROLES.SUPER_ADMIN
  ];
};

export const isRoleHigherOrEqual = (role1: UserRole, role2: UserRole): boolean => {
  const hierarchy = getRoleHierarchy();
  const index1 = hierarchy.indexOf(role1);
  const index2 = hierarchy.indexOf(role2);
  return index1 >= index2;
};